[theme]
primaryColor = "#3B82F6"        # Blue (buttons, sliders, highlights)
backgroundColor = "#F8FBFF"     # Very light blue background
secondaryBackgroundColor = "#93BCD2"  # White cards/containers
textColor = "#1E293B"           # Dark navy text
font = "sans serif"